export const FETCH_VACCINE_TOTAL = "FETCH_VACCINE_TOTAL";
export const FETCH_VACCINE_COUNTRY = "FETCH_VACCINE_COUNTRY";
export const FETCH_VIRUS_HISTORY_TOTAL = "FETCH_VIRUS_HISTORY_TOTAL";
export const FETCH_VIRUS_COUNTRY_HISTORY = "FETCH_VIRUS_COUNTRY_HISTORY";
export const FETCH_VIRUS_TOTAL_TODAY = "FETCH_VIRUS_TOTAL_TODAY";
export const FETCH_VIRUS_COUNTRY_TODAY = "FETCH_VIRUS_COUNTRY_TODAY";

export const SET_SELECTED_COUNTRY = "SET_SELECTED_COUNTRY";
export const SET_OPERATION_ERROR = "SET_OPERATION_ERROR";

export const FETCH_ARTICLES = "FETCH_ARTICLES";
